### ISSUE TITLE
Create Dockerfile

### ISSUE THREAD

**Issue by ArthB94** [loubruness/FeedFront#1]

**Comment by hugopanel** [comment]
Added dockerfiles in commit 0a1e477 on branch add-docker.

**Comment by hugopanel** [comment]
Added the script by @ArthB94 in commit c1fb8d3.
[See file](https://github.com/loubruness/FeedFront/blob/c1fb8d3870b1d4b18d839a7314518b7623512d59/internal-db-init.sql)
